const featuredTools = [
  {
    id: 'pindou',
    title: '拼豆',
    desc: '图片转 MARD 色号拼豆图纸',
    icon: 'image',
    iconColor: '#a85b52',
    tone: 'coral',
    category: '图片处理',
    path: '/pages/pindou/pindou',
    keywords: ['拼豆', '拼豆图纸', '像素画', '像素图', 'MARD', '迈阿德', '色号', '豆豆图纸', '照片转拼豆'],
  },
]

const hotTools = [
  {
    id: 'long-image',
    title: '长图拼接',
    desc: '多张截图合成一张长图',
    icon: 'image',
    iconColor: '#4f5fa8',
    tone: 'indigo',
    category: '图片处理',
    path: '/pages/long-image/long-image',
    keywords: ['长图', '拼接', '截图', '聊天记录', '订单截图', '图片拼接', '长截图'],
  },
  {
    id: 'qrcode',
    title: '二维码生成',
    desc: '快速生成各类美化码',
    icon: 'qrcode',
    iconColor: '#2f7567',
    tone: 'mint',
    category: '图片处理',
    path: '/pages/qrcode/qrcode',
    keywords: ['二维码', '生成', '扫码', '美化码', '链接'],
  },
  {
    id: 'mortgage',
    title: '房贷计算器',
    desc: '最新利率组合贷算力',
    icon: 'houses',
    iconColor: '#9a6a19',
    tone: 'amber',
    category: '生活计算',
    path: '/pages/mortgage/mortgage',
    keywords: ['房贷', '贷款', '利率', '月供', '组合贷'],
  },
  {
    id: 'salary',
    title: '工资计算器',
    desc: '税后到手一键估算',
    icon: 'wallet',
    iconColor: '#6655a6',
    tone: 'violet',
    category: '生活计算',
    path: '/pages/salary/salary',
    keywords: ['工资', '薪资', '税后', '个税', '五险一金', '到手工资'],
  },
  {
    id: 'social-security-card',
    title: '电子社保卡',
    desc: '社保查询与医保码',
    iconImage: '/assets/icons/social-security-card.png',
    iconBg: 'white',
    tone: 'red',
    category: '民生服务',
    shortLink: '#小程序://电子社保卡/Tm6FppEAraGw4Hg',
    keywords: ['电子社保卡', '社保', '医保', '医保码', '社保卡', '民生服务'],
  },
  {
    id: 'nine-grid',
    title: '九宫格切图',
    desc: '一键切朋友圈九宫格',
    icon: 'image',
    iconColor: '#c4622d',
    tone: 'coral',
    category: '图片处理',
    path: '/pages/nine-grid/nine-grid',
    keywords: ['九宫格', '切图', '朋友圈', '方图', '3x3', '九格图', '图片分割'],
  },
]

// 更多工具 - 可搜索，不在首页展示
const moreTools = [
  {
    id: 'restaurant',
    title: '餐饮投资计算器',
    desc: '开店成本、保本和经营分析',
    icon: 'shop',
    iconColor: '#24584d',
    tone: 'deep',
    category: '经营计算',
    path: '/pages/restaurant/restaurant',
    keywords: ['餐饮', '餐饮开店', '开店', '投资', '建店成本', '盈亏平衡', '经营分析', '保本'],
  },
  {
    id: 'image-compress',
    title: '图片压缩',
    desc: '清晰压缩证件照素材',
    icon: 'file-zip',
    iconColor: '#4d7b35',
    tone: 'green',
    category: '图片处理',
    path: '/pages/image-compress/image-compress',
    keywords: ['图片', '压缩', '证件照', '素材', '体积'],
  },
  {
    id: 'image-resize',
    title: '图片尺寸调整',
    desc: '裁成指定尺寸，可选 JPG 或 PNG',
    icon: 'frame',
    iconColor: '#2d6895',
    tone: 'sky',
    category: '图片处理',
    path: '/pages/image-resize/image-resize',
    keywords: ['图片尺寸', '证件照', '裁切', '改尺寸', '报名照', '头像', '像素', '一寸照', '二寸照'],
  },
  {
    id: 'image-watermark',
    title: '图片加水印',
    desc: '给证件和材料图加用途水印',
    icon: 'secured',
    iconColor: '#2f7567',
    tone: 'mint',
    category: '图片处理',
    path: '/pages/image-watermark/image-watermark',
    keywords: ['图片水印', '加水印', '证件水印', '办理银行卡', '银行卡专用', '幼儿园入园', '入园专用', '租房专用', '他用无效', '身份证水印', '材料水印'],
  },
  {
    id: 'video-compress',
    title: '视频压缩',
    desc: '本地压缩视频，减小发送体积',
    icon: 'video',
    iconColor: '#5d67d8',
    tone: 'indigo',
    category: '视频处理',
    path: '/pages/video-compress/video-compress',
    keywords: ['视频', '压缩', '视频压缩', '体积', '发送', '相册', '本地处理'],
  },
  {
    id: 'service-12333',
    title: '12333',
    desc: '人社服务查询与办理入口',
    iconImage: '/assets/icons/service-12333.png',
    iconBg: 'white',
    tone: 'red',
    category: '民生服务',
    shortLink: '#小程序://12333/FbL4BBX7Mt37teF',
    keywords: ['12333', '人社', '社保', '养老', '就业', '劳动', '民生服务'],
  },
  {
    id: 'national-service-platform',
    title: '国家政务服务平台',
    desc: '政务服务、证照和办事入口',
    iconImage: '/assets/icons/national-service-platform.png',
    iconBg: 'white',
    tone: 'red',
    category: '民生服务',
    shortLink: '#小程序://国家政务服务平台/TKudDlu2oipvrYC',
    keywords: ['国家政务服务平台', '政务', '办事', '证照', '社保', '医保', '公积金', '民生服务'],
  },
  {
    id: 'converter',
    title: '单位换算',
    desc: '长度面积重量快捷换',
    icon: 'measurement',
    iconColor: '#a85b52',
    tone: 'coral',
    category: '日常计算',
    path: '/pages/converter/converter',
    keywords: ['单位', '换算', '长度', '面积', '重量', '体积', '温度'],
  },
  {
    id: 'ruler',
    title: '校准尺子',
    desc: '用卡片校准屏幕刻度，测量更可靠',
    icon: 'measurement',
    iconColor: '#2d7467',
    tone: 'mint',
    category: '日常计算',
    path: '/pages/ruler/ruler',
    keywords: ['尺子', '测量', '长度', '厘米', '毫米', '屏幕尺子', '校准尺子', '银行卡', '身份证'],
  },
  {
    id: 'price-compare',
    title: '比价计算器',
    desc: '按规格算单价，快速看哪个更划算',
    icon: 'discount',
    iconColor: '#b66f18',
    tone: 'amber',
    category: '生活计算',
    path: '/pages/price-compare/price-compare',
    keywords: ['比价', '单价', '哪个便宜', '哪个划算', '购物', '克价', '斤价', '毫升价', '价格比较'],
  },
  {
    id: 'retirement-pension',
    title: '养老金估算器',
    desc: '估算退休后每月养老金',
    icon: 'wallet',
    iconColor: '#3f7a4b',
    tone: 'green',
    category: '生活计算',
    path: '/pages/retirement-pension/retirement-pension',
    keywords: ['退休', '养老金', '退休工资', '退休金', '养老保险', '养老金估算器', '退休工资计算器', '社保退休', '计发月数'],
  },
  {
    id: 'retirement-age',
    title: '退休年龄计算器',
    desc: '按出生日期估算退休年月',
    icon: 'calendar',
    iconColor: '#2d6895',
    tone: 'sky',
    category: '生活计算',
    path: '/pages/retirement-age/retirement-age',
    keywords: ['退休年龄', '延迟退休', '退休时间', '退休年月', '法定退休年龄', '出生年月', '退休计算', '养老金'],
  },
  {
    id: 'date-diff',
    title: '日期间隔计算器',
    desc: '算相差天数，也能推算前后日期',
    icon: 'calendar',
    iconColor: '#2d6895',
    tone: 'sky',
    category: '生活计算',
    path: '/pages/date-diff/date-diff',
    keywords: ['日期', '间隔', '天数', '相差几天', '倒计时', '纪念日', '前后日期', '工作日', '日期计算'],
  },
  {
    id: 'bmi',
    title: 'BMI 计算',
    desc: '科学评估身体健康指标',
    icon: 'heart',
    iconColor: '#2d6895',
    tone: 'sky',
    category: '生活健康',
    path: '/pages/bmi/bmi',
    keywords: ['bmi', '体重', '身高', '健康', '指数'],
  },
  {
    id: 'bmr',
    title: '基础代谢率',
    desc: '了解身体每日基础消耗',
    icon: 'activity',
    iconColor: '#c4622d',
    tone: 'coral',
    category: '生活健康',
    path: '/pages/bmr/bmr',
    keywords: ['bmr', '基础代谢', '代谢率', '热量', '卡路里', '每日消耗'],
  },
  {
    id: 'relationship',
    title: '亲戚关系计算器',
    desc: '快速算出称呼，姑舅姨表不再卡壳',
    icon: 'usergroup',
    iconColor: '#8b5a4a',
    tone: 'coral',
    category: '生活计算',
    path: '/pages/relationship/relationship',
    keywords: ['亲戚', '称呼', '关系', '家庭', '家族', '姑妈', '舅舅', '姨妈', '表哥', '堂姐'],
  },
  {
    id: 'compound',
    title: '复利 / 定投计算器',
    desc: '估算长期复利增长和每月定投结果',
    icon: 'saving-pot',
    iconColor: '#3f7a4b',
    tone: 'green',
    category: '理财计算',
    path: '/pages/compound/compound',
    keywords: ['复利', '定投', '理财', '投资', '基金', '本金', '收益率', '年化', '长期投资'],
  },
  {
    id: 'zodiac',
    title: '星座计算器',
    desc: '输入生日快速查询十二星座',
    icon: 'star-filled',
    iconColor: '#f0c36b',
    tone: 'indigo',
    category: '生活娱乐',
    path: '/pages/zodiac/zodiac',
    keywords: ['星座', '生日', '十二星座', '白羊座', '金牛座', '双子座', '巨蟹座', '狮子座', '处女座', '天秤座', '天蝎座', '射手座', '摩羯座', '水瓶座', '双鱼座'],
  },
  {
    id: 'choice-helper',
    title: '选择困难助手',
    desc: '模板优先帮你做决定',
    icon: 'app',
    iconColor: '#c4662d',
    tone: 'coral',
    category: '生活娱乐',
    path: '/pages/choice-helper/choice-helper',
    keywords: ['选择困难', '随机决定', '今天吃什么', '喝什么', '周末做什么', '谁来做', '随机选择'],
  },
  {
    id: 'sky-stardust',
    title: 'Sky星尘',
    desc: '光遇游戏攻略工具',
    iconImage: '/assets/icons/sky-stardust.png',
    tone: 'indigo',
    shortLink: '#小程序://Sky星尘/XHNcq07v6tucvth',
    category: '游戏工具',
    keywords: ['Sky星尘', '光遇', '攻略', '游戏工具', 'Sky', '星尘'],
  },
  {
    id: 'shelf-life',
    title: '商品保质期计算器',
    desc: '快速算出到期日和剩余天数',
    icon: 'calendar',
    iconColor: '#b67f2e',
    tone: 'amber',
    category: '生活计算',
    path: '/pages/shelf-life/shelf-life',
    keywords: ['保质期', '到期', '过期', '商品', '食品', '生产日期', '有效期', '保鲜'],
  },
  {
    id: 'poker-ledger',
    title: '打牌记账',
    desc: '本地记输赢，自动结算谁付谁',
    icon: 'money',
    iconColor: '#6655a6',
    tone: 'violet',
    category: '棋牌工具',
    path: '/pages/poker-ledger/poker-ledger',
    keywords: ['打牌', '麻将', '扑克', '记账', '牌局', '结算', '输赢', '谁付谁'],
  },
]

const topicCards = [
  {
    id: 'guide',
    label: '新手必读',
    title: '小白工具箱使用指南',
    desc: '快速了解搜索、热门工具和高频能力的使用方式',
    icon: 'book-open',
    iconColor: '#24584d',
    button: '查看指南',
    tone: 'deep',
    pressKey: 'topic-guide',
    category: '使用指南',
    path: '/pages/guide/guide',
    keywords: ['指南', '教程', '使用', '帮助', '新手'],
  },
]

const toolCatalog = [
  ...featuredTools.map((item) => ({
    ...item,
    type: 'tool',
    actionText: '打开工具',
  })),
  ...hotTools.map((item) => ({
    ...item,
    type: 'tool',
    actionText: item.shortLink ? '跳转小程序' : '打开工具',
  })),
  ...moreTools.map((item) => ({
    ...item,
    type: 'tool',
    actionText: item.shortLink ? '跳转小程序' : '打开工具',
  })),
  ...topicCards.map((item) => ({
    ...item,
    type: 'topic',
    actionText: '查看专题',
  })),
]

const normalize = (value) => String(value || '').trim().toLowerCase()

const getSearchText = (item) => [
  item.title,
  item.desc,
  item.category,
  ...(item.keywords || []),
].join(' ').toLowerCase()

const searchTools = (keyword) => {
  const query = normalize(keyword)

  if (!query) {
    return toolCatalog
  }

  return toolCatalog.filter((item) => getSearchText(item).includes(query))
}

module.exports = {
  featuredTools,
  hotTools,
  moreTools,
  topicCards,
  toolCatalog,
  searchTools,
}
